### ISSUE TITLE
Bug: undefined symbol: PyCObject_FromVoidPtr

### ISSUE THREAD

**Issue by andrevmatos** [snoack/ssh4py#1]
Hi. If this isn't right place to do this, delete this post. I'm a brazillian developer, computer engineering student of 3rd period at State University of Campinas (Unicamp), Brazil, and python developer at Itautec Inc. I want to help with development, and as first contribution:
I tryed to install git version at Arch Linux 64bits, with own PKGBUILD, libssh2=1.2.7, zlib=1.2.5 and python=3.2, and got this error on python import libssh2:
<code>>>> import libssh2
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
ImportError: /usr/lib/python3.2/site-packages/libssh2.cpython-32mu.so: undefined symbol: PyCObject_FromVoidPtr

> > > </code>
> > > Unfortunatelly, I'm not a expert on C python extensions, and can't fix this bug. 
> > > Thanks very much.
> > > Att,

**Comment by Krejdom** [comment]
Hi, where can I find the release with this issue fixed?
